
package gui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.rmi.RemoteException;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;

import com.toedter.calendar.JDateChooser;

import entity.*;
import dao.*;
import entity.NhanVien;
import impl.NhanVienImpl;
import impl.TaiKhoanImpl;
import jakarta.persistence.EntityManager;
import jakarta.persistence.Persistence;

import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;



import dao.Regex;
//import Dao.DAOPhatSinhMa;



/**
 *
 * @author Asus
 */
public class FRMNhanVien extends JFrame implements ActionListener, MouseListener, FocusListener, KeyListener {

    private static final long serialVersionUID = 1L;

	private NhanVien nv;
	private Regex regex;
//	private DAOPhatSinhMa daoPhatSinhMa;
	private DAOSinhMaTuDong daoPhatSinhMa ;
	private Date dNgayHienTai;
	private LocalDate now;
	private Date dNow;
	private int nam, thang, ngay;
	private JDateChooser chooserNgaySinh;
	private SimpleDateFormat dfNgaySinh;



	/**
     * Creates new form FRMNhanVien
     */
    public FRMNhanVien() {
        try {
            initComponents();
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
    }
    public static NhanVienDao nhanVienDao;

	static {
		try {
			nhanVienDao = new NhanVienImpl();
		} catch (RemoteException e) {
			throw new RuntimeException(e);
		}
	}
	public static TaiKhoanDao taiKhoanDao;
	static {
		try {
			taiKhoanDao = new TaiKhoanImpl();
		} catch (RemoteException e) {
			throw new RuntimeException(e);
		}
	}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws RemoteException
     */
    @SuppressWarnings({ "unchecked", "deprecation" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws RemoteException {


		/**
		 * Káº¿t ná»‘i database
		 */
    	EntityManager entityManager = Persistence.createEntityManagerFactory("maria").createEntityManager();

		/**
		 * Khai bÃ¡o cÃ¡c DAO
		 */


        daoPhatSinhMa = new DAOSinhMaTuDong();

//		regex = new Regex();

		/**
		 * Äá»‹nh dáº¡ng ngÃ y, lÆ°Æ¡ng trong báº£ng
		 */
		dfNgaySinh=new SimpleDateFormat("dd/MM/yyyy");


        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcboGtinh = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jcboChucVu = new javax.swing.JComboBox<>();
        txtHoTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelCaLamViec = new javax.swing.JLabel();
        jcboCaLamViec = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        jpnSapXep1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        rdoTheoMaNV = new javax.swing.JRadioButton();
        rdoTheoTenNV = new javax.swing.JRadioButton();
        rdoTheoChucVuNV = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNV = new javax.swing.JTable();
        btnThemNV = new javax.swing.JButton();
        btnSuaNV = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        jbTimNV = new javax.swing.JButton();
        jbLocNV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setPreferredSize(new java.awt.Dimension(1202, 422));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Há» vÃ  TÃªn: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("SDT: ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Äá»‹a Chá»‰: ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("CCCD: ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("NgÃ y sinh: ");
		chooserNgaySinh = new JDateChooser();
		chooserNgaySinh.getCalendarButton().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		chooserNgaySinh.setBounds(110, 213, 191, 25);
		chooserNgaySinh.setDateFormatString("dd/MM/yyyy");
		chooserNgaySinh.setDate(dNgayHienTai);
		chooserNgaySinh.setBorder(new LineBorder(new Color(114, 23, 153), 1, true));
		chooserNgaySinh.setFont(new Font("SansSerif", Font.PLAIN, 15));
		chooserNgaySinh.getCalendarButton().setPreferredSize(new Dimension(30, 24));
		chooserNgaySinh.getCalendarButton().setBackground(new Color(102, 0, 153));
		chooserNgaySinh.getCalendarButton().setToolTipText("Chá»n ngÃ y sinh");

		now = LocalDate.now();
		ngay = now.getDayOfMonth();
		thang = now.getMonthValue()-1;
		nam = now.getYear()-1900;
		dNow = new Date(nam, thang, ngay);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Giá»›i tÃ­nh");

        jcboGtinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Ná»¯" }));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Chá»©c vá»¥:");

        jcboChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quáº£n LÃ½", "NhÃ¢n ViÃªn" }));
        jcboChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboChucVuActionPerformed(evt);
            }
        });

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("MÃ£ NV: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("THÃ”NG TIN NHÃ‚N VIÃŠN");

        jLabelCaLamViec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCaLamViec.setText("Ca lÃ m:");

        jcboCaLamViec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcboCaLamViec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jcboCaLamViec.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcboCaLamViecItemStateChanged(evt);
            }
        });
        jcboCaLamViec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboCaLamViecActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)))
                                .addGap(11, 11, 11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jcboGtinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCaLamViec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcboCaLamViec, 0, 1, Short.MAX_VALUE))
                            .addComponent(txtCCCD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(txtDiaChi)
                            .addComponent(txtMaNV)
                            .addComponent(txtSDT)
                            .addComponent(txtHoTen)
                            .addComponent(chooserNgaySinh)
                            .addComponent(jcboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooserNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboGtinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabelCaLamViec)
                    .addComponent(jcboCaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("TÃ¬m kiáº¿m");
		txtTim.setText("TÃ¬m nhÃ¢n viÃªn theo mÃ£ nhÃ¢n viÃªn, tÃªn nhÃ¢n viÃªn, sÄ‘t, ca lÃ m viá»‡c.");

        jpnSapXep1.setBackground(new java.awt.Color(255, 255, 255));
        jpnSapXep1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel17.setText("Sáº¯p Xáº¿p");

        rdoTheoMaNV.setBackground(new java.awt.Color(255, 153, 204));
        rdoTheoMaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoTheoMaNV.setText("Theo MÃ£");

        rdoTheoTenNV.setBackground(new java.awt.Color(255, 153, 204));
        rdoTheoTenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoTheoTenNV.setText("Theo TÃªn");

        rdoTheoChucVuNV.setBackground(new java.awt.Color(255, 153, 204));
        rdoTheoChucVuNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdoTheoChucVuNV.setText("Chá»©c Vá»¥");

        javax.swing.GroupLayout jpnSapXep1Layout = new javax.swing.GroupLayout(jpnSapXep1);
        jpnSapXep1.setLayout(jpnSapXep1Layout);
        jpnSapXep1Layout.setHorizontalGroup(
            jpnSapXep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSapXep1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(rdoTheoMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(rdoTheoTenNV)
                .addGap(78, 78, 78)
                .addComponent(rdoTheoChucVuNV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnSapXep1Layout.setVerticalGroup(
            jpnSapXep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSapXep1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnSapXep1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoTheoMaNV)
                    .addComponent(rdoTheoTenNV)
                    .addComponent(rdoTheoChucVuNV)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
//        jTableNV.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null}
//            },
//            new String [] {
//                "MÃ£ NV", "Há» tÃªn", "SÄT", "Äá»‹a chá»‰", "CCCD", "NgÃ y sinh", "Giá»›i tÃ­nh", "Chá»©c vá»¥"
//            }
//        ));
        jScrollPane1.setViewportView(jTableNV);

        String col[] = {
              "MÃ£ NV", "Há» tÃªn", "SÄT", "Äá»‹a chá»‰", "CCCD", "NgÃ y sinh", "Giá»›i tÃ­nh", "Chá»©c vá»¥"
          };
		modelNV = new DefaultTableModel(col, 0);
		jTableNV = new JTable(modelNV);
        jScrollPane1.setViewportView(jTableNV);
        loadDanhSachNV();

        btnThemNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThemNV.setIcon(new javax.swing.ImageIcon("D:\\Desktop\\HocTap\\HocKi2_Nam 4_(2024_2025)\\LTPT_Java\\THNhom\\New folder\\BaiTapLonPhanTan\\iCon\\add.png")); // NOI18N
        btnThemNV.setText("ThÃªm");

        btnSuaNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSuaNV.setIcon(new javax.swing.ImageIcon("D:\\Desktop\\HocTap\\HocKi2_Nam 4_(2024_2025)\\LTPT_Java\\THNhom\\New folder\\BaiTapLonPhanTan\\iCon\\service.png")); // NOI18N
        btnSuaNV.setText("Sá»­a");

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon("D:\\Desktop\\HocTap\\HocKi2_Nam 4_(2024_2025)\\LTPT_Java\\THNhom\\New folder\\BaiTapLonPhanTan\\iCon\\refresh.png")); // NOI18N
        btnLamMoi.setText("LÃ m Má»›i");


        btnXoaNV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnXoaNV.setIcon(new javax.swing.ImageIcon("D:\\Desktop\\HocTap\\HocKi2_Nam 4_(2024_2025)\\LTPT_Java\\THNhom\\New folder\\BaiTapLonPhanTan\\iCon\\delete.png")); // NOI18N
        btnXoaNV.setText("XÃ³a");
        jbTimNV.setIcon(new javax.swing.ImageIcon("D:\\Desktop\\HocTap\\HocKi2_Nam 4_(2024_2025)\\LTPT_Java\\THNhom\\New folder\\BaiTapLonPhanTan\\iCon\\search.png")); // NOI18N

        jbLocNV.setIcon(new javax.swing.ImageIcon("D:\\Desktop\\HocTap\\HocKi2_Nam 4_(2024_2025)\\LTPT_Java\\THNhom\\New folder\\BaiTapLonPhanTan\\iCon\\sorting.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnThemNV)
                .addGap(104, 104, 104)
                .addComponent(btnSuaNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnLamMoi)
                .addGap(103, 103, 103)
                .addComponent(btnXoaNV)
                .addGap(63, 63, 63))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpnSapXep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbLocNV, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTimNV, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbTimNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbLocNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnSapXep1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNV)
                    .addComponent(btnSuaNV)
                    .addComponent(btnLamMoi)
                    .addComponent(btnXoaNV))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1214, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnGr = new ButtonGroup();
        btnGr.add(rdoTheoChucVuNV);
        btnGr.add(rdoTheoMaNV);
        btnGr.add(rdoTheoTenNV);
        txtMaNV.setEnabled(false);

        pack();

		/**
		 * CÃ¡c sá»± kiá»‡n cá»§a giao diá»‡n quáº£n lÃ½ nhÃ¢n viÃªn
		 */
		loadDanhSachNV();

		txtTim.addFocusListener(this);

		jcboCaLamViec.addActionListener(this);

		jbTimNV.addActionListener(this);
		btnThemNV.addActionListener(this);
		btnSuaNV.addActionListener(this);
		btnXoaNV.addActionListener(this);
		btnLamMoi.addActionListener(this);

		rdoTheoMaNV.addActionListener(this);
		rdoTheoTenNV.addActionListener(this);
		rdoTheoChucVuNV.addActionListener(this);

		jTableNV.addMouseListener(this);

		txtTim.addKeyListener(this);
		jbTimNV.addKeyListener(this);
		btnLamMoi.addKeyListener(this);
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMNhanVien().setVisible(true);
            }
        });
    }


	/**
	 *Code sá»± kiá»‡n
	 */
	public void actionPerformed(ActionEvent e) {
		Object o = e.getSource();
		//tÃ¬m NV
		/*if(o.equals(jbTimNV)) {
			if(txtTim.getText().equals("") || txtTim.getText().equals("TÃ¬m nhÃ¢n viÃªn theo mÃ£ nhÃ¢n viÃªn, tÃªn nhÃ¢n viÃªn, sÄ‘t, ca lÃ m viá»‡c.")) {
				removeDanhSachNV(modelNV);
				JOptionPane.showMessageDialog(this, "Vui lÃ²ng nháº­p thÃ´ng tin tÃ¬m kiáº¿m!", "ThÃ´ng bÃ¡o", JOptionPane.WARNING_MESSAGE);
				txtTim.requestFocus();
			}
			else {
				try {
					findNV();
				} catch (RemoteException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
				txtTim.selectAll();
			}
		}
*/
		//thÃªm NV
		if(o.equals(btnThemNV)) {
            try {
                addNV();
            } catch (RemoteException ex) {
                throw new RuntimeException(ex);
            }
        }

		//sá»­a NV
		if(o.equals(btnSuaNV)) {
			updateNV();
		}

		//há»§y tÃ i khoáº£n NV
		if(o.equals(btnXoaNV)) {
			xoaNV();
			removeDanhSachNV(modelNV);
			try {
				loadDanhSachNV();
			} catch (RemoteException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}

		//lÃ m má»›i
		if(o.equals(btnLamMoi)) {
			resetAll();
			//bg.clearSelection();
			removeDanhSachNV(modelNV);
			try {
				loadDanhSachNV();
			} catch (RemoteException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}

		if(o.equals(rdoTheoMaNV)) {
			removeDanhSachNV(modelNV);
			try {
				loadDanhSachCaNV(nhanVienDao.sortMaNV("ASC"));
			} catch (RemoteException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}

		if(o.equals(rdoTheoChucVuNV)&& o.equals(jbLocNV)) {
			removeDanhSachNV(modelNV);
			try {
				loadDanhSachNV(nhanVienDao.sortCV("ASC"));
			} catch (RemoteException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			};
		}
	}
	private void removeDanhSachNV(DefaultTableModel defaultTableModel) {
		while(jTableNV.getRowCount() > 0){
			modelNV.removeRow(0);
		}
	}

	/**
	 * XÃ³a tráº¯ng textfield vÃ  textarea, Ä‘áº·t láº¡i máº·c Ä‘á»‹nh cÃ¡c combobox vÃ  cÃ¡c button
	 */
	private void resetAll() {
		txtTim.setText("TÃ¬m nhÃ¢n viÃªn theo mÃ£ nhÃ¢n viÃªn, tÃªn nhÃ¢n viÃªn, sÄ‘t, ca lÃ m viá»‡c.");
		txtMaNV.setText("");
		txtHoTen.setText("");
		txtSDT.setText("");
		txtDiaChi.setText("");
		txtCCCD.setText("");
		chooserNgaySinh.setDate(dNow);

		jcboChucVu.setSelectedItem("Quáº£n lÃ½");
		jcboGtinh.setSelectedItem("Nam");
		jcboCaLamViec.setSelectedItem("1");

		rdoTheoMaNV.setSelected(false);
		rdoTheoTenNV.setSelected(false);
		rdoTheoChucVuNV.setSelected(false);

		txtHoTen.requestFocus();
	}


	/**
	 * Sá»± kiá»‡n tÃ¬m kiáº¿m thÃ´ng tin nhÃ¢n viÃªn
	 */
//	private void findNV() throws RemoteException {
//		String input = txtTim.getText().trim();
//		input = input.toUpperCase();
//		ArrayList<NhanVien> lstNV = null;
//
//		String regexMaNV = "^((NV|nv)[0-9]{3})$";
//		String regexTenNV= "^[ A-Za-za-zA-ZÃ€ÃÃ‚ÃƒÃˆÃ‰ÃŠÃŒÃÃ’Ã“Ã”Ã•Ã™ÃšÄ‚ÄÄ¨Å¨Æ Ã Ã¡Ã¢Ã£Ã¨Ã©ÃªÃ¬Ã­Ã²Ã³Ã´ÃµÃ¹ÃºÄƒÄ‘Ä©Å©Æ¡Æ¯Ä‚áº áº¢áº¤áº¦áº¨áºªáº¬áº®áº°áº²áº´áº¶áº¸áººáº¼á»€á»€á»‚áº¾Æ°Äƒáº¡áº£áº¥áº§áº©áº«áº­áº¯áº±áº³áºµáº·áº¹áº»áº½á»á»á»ƒáº¿á»„á»†á»ˆá»Šá»Œá»Žá»á»’á»”á»–á»˜á»šá»œá»žá» á»¢á»¤á»¦á»¨á»ªá»…á»‡á»‰á»‹á»á»á»‘á»“á»•á»—á»™á»›á»á»Ÿá»¡á»£á»¥á»§á»©á»«á»¬á»®á»°á»²á»´Ãá»¶á»¸á»­á»¯á»±á»³á»µá»·á»¹]+$";
//		String regexSDT  = "^(0[0-9]{9})$";
//		String regexCa   = "^((ca)[1-3]{1}$";
//
//		if( regex.regexTimNV(input) ) {
//			if(input.matches(regexMaNV)) {
//				lstNV = nhanVienDao.getMaVaSdtNVChoDDP(input);
//
//				loadDanhSachMaVaSdtNV(lstNV);
//			}
//			else if(input.matches(regexTenNV)) {
//				lstNV = nhanVienDao.getTenNV(input);
//				loadDanhSachTenNV(lstNV);
//			}
//			else if(input.matches(regexSDT)) {
//				lstNV = nhanVienDao.getMaVaSdtNVChoDDP(input);
//				loadDanhSachMaVaSdtNV(lstNV);
//			}else if(input.matches(regexCa)) {
//				lstNV = nhanVienDao.getCaNV(input);
//				loadDanhSachCaNV(lstNV);
//			}
//			if(lstNV.size()==0) {
//				JOptionPane.showMessageDialog(this, "KhÃ´ng tÃ¬m tháº¥y thÃ´ng tin tÃ¬m kiáº¿m phÃ¹ há»£p!", "ThÃ´ng bÃ¡o", JOptionPane.ERROR_MESSAGE);
//				txtTim.requestFocus();
//				txtTim.selectAll();
//			}
//		}
//	}
//

	/**
	 * Hiá»‡n danh sÃ¡ch thÃ´ng tin nhÃ¢n viÃªn Ä‘ang lÃ m viá»‡c tá»« mÃ£ NV gá»“m:
	 * mÃ£ NV, tÃªn NV, sÄ‘t, Ä‘á»‹a chá»‰, cccd, ngaySinh, gioiTinh, chucVu
	 * @paramnv
	 */
	public void loadDanhSachNV() throws RemoteException {
		removeDanhSachNV(modelNV);
		ArrayList<NhanVien> dsNV = nhanVienDao.getDanhSachNV();
		for (NhanVien nv : dsNV) {
			String ngaySinh = "";
			if(nv.getNgaySinh() != null)
				ngaySinh = dfNgaySinh.format(nv.getNgaySinh());

			modelNV.addRow(new Object[] {
					nv.getMaNhanVien(), nv.getTenNhanVien(), nv.getSdt(), nv.getDiaChi(),
					 nv.getCccd(), ngaySinh, nv.getGioiTinh(), nv.getChucVu()
			});
		}
	}
	public void loadDanhSachNV(ArrayList<NhanVien> dsNV) {

		for (NhanVien nv : dsNV) {
			String ngaySinh = "";
			if(nv.getNgaySinh() != null)
				ngaySinh = dfNgaySinh.format(nv.getNgaySinh());

			modelNV.addRow(new Object[] {
					nv.getMaNhanVien(), nv.getTenNhanVien(), nv.getSdt(), nv.getDiaChi(),
					 nv.getCccd(), ngaySinh, nv.getGioiTinh(), nv.getChucVu()
			});
		}
	}


    private void loadDanhSachTenNV(ArrayList<NhanVien> lstNV) throws RemoteException {
		// TODO Auto-generated method stub
		removeDanhSachNV(modelNV);
		ArrayList<NhanVien> lstName = nhanVienDao.getTenNV(txtTim.getText().trim());
		for(NhanVien nv : lstName) {
			modelNV.addRow(new Object[] {
					nv.getMaNhanVien(), nv.getTenNhanVien(), nv.getSdt(), nv.getDiaChi(),
					 nv.getCccd(), dfNgaySinh.format(nv.getNgaySinh()), nv.getGioiTinh(), nv.getChucVu()
			});
		}
	}

	private void loadDanhSachMaVaSdtNV(ArrayList<NhanVien> lstNV) throws RemoteException {
		// TODO Auto-generated method stub
		removeDanhSachNV(modelNV);
		ArrayList<NhanVien> lstMa = nhanVienDao.getMaVaSdtNVChoDDP1(txtTim.getText().toLowerCase().trim());
		for(NhanVien nv : lstMa) {
			modelNV.addRow(new Object[] {
					nv.getMaNhanVien(), nv.getTenNhanVien(), nv.getSdt(), nv.getDiaChi(),
					 nv.getCccd(), dfNgaySinh.format(nv.getNgaySinh()), nv.getGioiTinh(), nv.getChucVu()
			});
		}
	}

	/**
	 * Hiá»‡n danh sÃ¡ch thÃ´ng tin NV theo ca lÃ m viá»‡c
	 * @param lstNV
	 */
	private void loadDanhSachCaNV(ArrayList<NhanVien> lstNV) throws RemoteException {
		removeDanhSachNV(modelNV);
		ArrayList<NhanVien> lstCa = nhanVienDao.getCaNV(txtTim.getText().trim());
		for(NhanVien nv : lstCa) {
			modelNV.addRow(new Object[] {
					nv.getMaNhanVien(), nv.getTenNhanVien(), nv.getSdt(), nv.getDiaChi(),
					 nv.getCccd(), dfNgaySinh.format(nv.getNgaySinh()), nv.getGioiTinh(), nv.getChucVu()
			});
		}
	}

	/**
	 * Sáº¯p xáº¿p theo mÃ£ NV tÄƒng dáº§n
	 * @paramnv
	 */
//	private void sortMaNVTangDan()  {
//		removeDanhSachNV(modelNV);
//		ArrayList<NhanVien> lstMa = nhanVienDao.sortMaNV("ASC");
//		for(NhanVien nv : lstMa) {
//			modelNV.addRow(new Object[] {
//					nv.getMaNhanVien(), nv.getTenNhanVien(), nv.getSdt(), nv.getDiaChi(),
//					 nv.getCccd(), dfNgaySinh.format(nv.getNgaySinh()), nv.getGioiTinh(), nv.getChucVu()
//			});
//		}
//	}

	/**
	 * Sáº¯p xáº¿p theo tÃªn NV tÄƒng dáº§n
	 * @paranv
	 */
//	private void sortTenNVTangDan()  {
//		removeDanhSachNV(modelNV);
//		ArrayList<NhanVien> lstTen = nhanVienDao.sortTen("ASC");
//		for(NhanVien nv : lstTen) {
//			modelNV.addRow(new Object[] {
//					nv.getMaNhanVien(), nv.getTenNhanVien(), nv.getSdt(), nv.getDiaChi(),
//					 nv.getCccd(), dfNgaySinh.format(nv.getNgaySinh()), nv.getGioiTinh(), nv.getChucVu()
//			});
//		}
//	}

	/**
	 * Sáº¯p xáº¿p chá»©c vá»¥ tÄƒng dáº§n: nhÃ¢n viÃªn, quáº£n lÃ½
	 * @paramnv
	 */
//	private void sortChucVuTangDan()  {
//		removeDanhSachNV(modelNV);
//		ArrayList<NhanVien> lstNhanVien = nhanVienDao.sortCV("NhÃ¢n viÃªn");
//		for(NhanVien nv : lstNhanVien) {
//			modelNV.addRow(new Object[] {
//					nv.getMaNhanVien(), nv.getTenNhanVien(), nv.getSdt(), nv.getDiaChi(),
//					 nv.getCccd(), dfNgaySinh.format(nv.getNgaySinh()), nv.getGioiTinh(), nv.getChucVu()
//			});
//		}
//
//		ArrayList<NhanVien> lstQL = nhanVienDao.sortCV("Quáº£n lÃ½");
//		for(NhanVien nv : lstQL) {
//			modelNV.addRow(new Object[] {
//					nv.getMaNhanVien(), nv.getTenNhanVien(), nv.getSdt(), nv.getDiaChi(),
//					 nv.getCccd(), dfNgaySinh.format(nv.getNgaySinh()), nv.getGioiTinh(), nv.getChucVu()
//			});
//		}
//	}

	protected void jcboChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboChucVuActionPerformed


	private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed

    private void jcboCaLamViecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboCaLamViecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboCaLamViecActionPerformed

    private void jcboCaLamViecItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcboCaLamViecItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboCaLamViecItemStateChanged

    public JPanel getNhanVien(){
       return jPanel5;
   }


	/**
	 * Táº¡o tÃ i khoáº£n nhÃ¢n viÃªn má»›i, thÃªm thÃ´ng tin nhÃ¢n viÃªn vÃ o cÆ¡ sá»Ÿ dá»¯ liá»‡u vÃ  hiá»‡n lÃªn báº£ng danh sÃ¡ch
	 */
	@SuppressWarnings("deprecation")
	private void addNV() throws RemoteException {

        String phatSinhMaNV = daoPhatSinhMa.getMaNV();
		String hoTen = txtHoTen.getText().trim();
		String sdt = txtSDT.getText().trim();
		String diaChi = txtDiaChi.getText().trim();
		String chucVu = jcboChucVu.getSelectedItem().toString();
		String cccd = txtCCCD.getText().trim();
		String gioiTinh = jcboGtinh.getSelectedItem().toString();

		java.util.Date date = chooserNgaySinh.getDate();
		Date ngaySinh = new Date(date.getYear(), date.getMonth(), date.getDate());
		int age = nam - ngaySinh.getYear();

		TaiKhoan tk=new TaiKhoan(phatSinhMaNV);
		String matKhau = phatSinhMaNV.concat(sdt);

		if(hoTen.equals("") || sdt.equals("") || diaChi.equals("") || cccd.equals("")) {
			JOptionPane.showMessageDialog(this, "Vui lÃ²ng nháº­p thÃ´ng tin Ä‘áº§y Ä‘á»§!", "ThÃ´ng bÃ¡o", JOptionPane.WARNING_MESSAGE);
			txtHoTen.requestFocus();
		}else {
			if(regex.regexTen(txtHoTen) && regex.regexSDT(txtSDT) && regex.regexDiaChi(txtDiaChi) && regex.regexCCCD(txtCCCD)) {
                try {
                    if(nhanVienDao.checkSdtNV(sdt)) {
                        if(nhanVienDao.checkCccdNV(cccd)) {
                            if(age>=18 && ngaySinh.getDate()>0 && ngaySinh.getDate()<=31 && ngaySinh.getMonth()>0 && ngaySinh.getMonth()<=12 && ngaySinh.getYear()>0 && ngaySinh.getYear()<nam) {
                                TaiKhoan tk1=new TaiKhoan();
                                tk1.setMaTK(phatSinhMaNV);
                                tk1.setMatKhau(matKhau);
                                taiKhoanDao.createTaiKhoan(tk1.getMaTK(), tk1.getMatKhau());

                                //them vao data
                                NhanVien nv=new NhanVien();
                                nv.setMaNhanVien(phatSinhMaNV);
                                nv.setTaiKhoan(tk);
                                nv.setTenNhanVien(hoTen);
                                nv.setChucVu(chucVu);
                                nv.setGioiTinh(gioiTinh);
                                nv.setNgaySinh(ngaySinh);
                                nv.setDiaChi(diaChi);
                                nv.setSdt(sdt);
                                nv.setCccd(cccd);
                                nv.setTrangThaiLamViec("Äang lÃ m viá»‡c");
                                if(jcboChucVu.getSelectedItem()=="Quáº£n lÃ½")
                                    nv.setLuong(10000000);
                                if(jcboChucVu.getSelectedItem()=="NhÃ¢n viÃªn")
                                    nv.setLuong(5000000);
                                new NhanVienImpl().themNhanVien(nv, tk1);

                                //them vao table
                                resetAll();
                                modelNV.addRow(new Object[] {
                                        nv.getMaNhanVien(), nv.getTenNhanVien(), nv.getSdt(), nv.getDiaChi(),
                                         nv.getCccd(), dfNgaySinh.format(nv.getNgaySinh()), nv.getGioiTinh(), nv.getChucVu()
                                });
                                String mkTK = "\nMáº­t kháº©u: "+matKhau;
                                JOptionPane.showMessageDialog(this, "ThÃªm thÃ nh cÃ´ng!\nMÃ£ tÃ i khoáº£n: "+phatSinhMaNV +mkTK, "ThÃ´ng bÃ¡o", JOptionPane.INFORMATION_MESSAGE);
                            } else
                                JOptionPane.showMessageDialog(this, "NhÃ¢n viÃªn lÃ m viá»‡c pháº£i trÃªn 18 tuá»•i!", "ThÃ´ng bÃ¡o", JOptionPane.WARNING_MESSAGE);
                        } else
                            JOptionPane.showMessageDialog(this, "CÄƒn cÆ°á»›c cÃ´ng dÃ¢n Ä‘Ã£ Ä‘Äƒng kÃ½", "ThÃ´ng bÃ¡o", JOptionPane.ERROR_MESSAGE);
                    } else
                        JOptionPane.showMessageDialog(this, "Sá»‘ Ä‘iá»‡n thoáº¡i Ä‘Ã£ Ä‘Äƒng kÃ½", "ThÃ´ng bÃ¡o", JOptionPane.ERROR_MESSAGE);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
		}
	}


	/**
	 * Há»§y tÃ i khoáº£n nhÃ¢n viÃªn, chuyá»ƒn tráº¡ng thÃ¡i Ä‘ang lÃ m viá»‡c thÃ nh Ä‘Ã£ nghá»‰ viá»‡c
	 * @return
	 */
	private boolean xoaNV() {
		int row = jTableNV.getSelectedRow();
		if(row > -1) {
			int cancel = JOptionPane.showConfirmDialog(null, "Báº¡n muá»‘n há»§y tÃ i khoáº£n nhÃ¢n viÃªn nÃ y?", "ThÃ´ng bÃ¡o", JOptionPane.YES_NO_OPTION);
			if(cancel == JOptionPane.YES_OPTION) {
				NhanVien nv=new NhanVien();
				String maNV = jTableNV.getValueAt(row, 0).toString();
				if(!maNV.equals(nv.getMaNhanVien())) {
					try {
						modelNV.removeRow(row);
                        boolean b = new NhanVienImpl().huyNV(maNV);
                        JOptionPane.showMessageDialog(null, "ÄÃ£ há»§y tÃ i khoáº£n!");
					} catch (RemoteException e) {
                        throw new RuntimeException(e);
                    }
                }else
					JOptionPane.showMessageDialog(this, "TÃ i khoáº£n nhÃ¢n viÃªn nÃ y khÃ´ng Ä‘Æ°á»£c há»§y vÃ¬ Ä‘ang Ä‘Äƒng nháº­p há»‡ thá»‘ng!", "ThÃ´ng bÃ¡o", JOptionPane.WARNING_MESSAGE);
			}
		}else {
			JOptionPane.showMessageDialog(null, "Vui lÃ²ng chá»n thÃ´ng tin tÃ i khoáº£n nhÃ¢n viÃªn cáº§n há»§y!", "ThÃ´ng bÃ¡o", JOptionPane.WARNING_MESSAGE);
		}
		return false;
	}



	/**
	 * Sá»­a, cáº­p nháº­t thÃ´ng tin nhÃ¢n viÃªn
	 */
	@SuppressWarnings("deprecation")
	private void updateNV() {
		int row = jTableNV.getSelectedRow();
		if(row>-1) {
			int update = JOptionPane.showConfirmDialog(this, "Báº¡n muá»‘n sá»­a thÃ´ng tin nhÃ¢n viÃªn nÃ y?", "ThÃ´ng bÃ¡o", JOptionPane.YES_NO_OPTION);
			if(update == JOptionPane.YES_OPTION) {
				NhanVien nv=new NhanVien();
				String maNV = (String) jTableNV.getValueAt(row, 0);
				java.util.Date date = chooserNgaySinh.getDate();
				Date ngaySinh=new Date(date.getYear(), date.getMonth(), date.getDate());
				int caLamViec = Integer.parseInt((String) jcboCaLamViec.getSelectedItem());
				try {
					if(regex.regexTen(txtHoTen) && regex.regexSDT(txtSDT) && regex.regexDiaChi(txtDiaChi) && regex.regexCCCD(txtCCCD)) {
						nv.setMaNhanVien(maNV);
						nv.setTenNhanVien(txtHoTen.getText());
						nv.setChucVu((String) jcboChucVu.getSelectedItem());
						nv.setGioiTinh((String) jcboGtinh.getSelectedItem());
						nv.setNgaySinh(ngaySinh);
						nv.setDiaChi(txtDiaChi.getText());
						nv.setSdt(txtSDT.getText());
						nv.setCccd(txtCCCD.getText());
						if(jcboChucVu.getSelectedItem()=="Quáº£n lÃ½")
							nv.setLuong(10000000);
						if(jcboChucVu.getSelectedItem()=="NhÃ¢n viÃªn")
							nv.setLuong(5000000);
						nv.setCaLamViec(caLamViec);

						new NhanVienImpl().capNhatNV(nv, maNV);

						removeDanhSachNV(modelNV);
						modelNV.setRowCount(0);
						modelNV.addRow(new Object[] {
								nv.getMaNhanVien(), nv.getTenNhanVien(), nv.getSdt(), nv.getDiaChi(),
								 nv.getCccd(), dfNgaySinh.format(nv.getNgaySinh()), nv.getGioiTinh(), nv.getChucVu()
						});
						JOptionPane.showMessageDialog(this, "ThÃ´ng tin nhÃ¢n viÃªn Ä‘Ã£ Ä‘Æ°á»£c sá»­a!", "ThÃ´ng bÃ¡o", JOptionPane.INFORMATION_MESSAGE);
					}
				}catch (RemoteException e) {
					e.printStackTrace();
					JOptionPane.showMessageDialog(null, "Chá»‰nh sá»­a thÃ´ng tin tháº¥t báº¡i!", "ThÃ´ng bÃ¡o", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
		else
			JOptionPane.showMessageDialog(null, "Vui lÃ²ng chá»n thÃ´ng tin nhÃ¢n viÃªn cáº§n sá»­a!", "ThÃ´ng bÃ¡o", JOptionPane.WARNING_MESSAGE);
	}


	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCaLamViec;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNV;
    private javax.swing.JButton jbLocNV;
    private javax.swing.JButton jbTimNV;
    private javax.swing.JComboBox<String> jcboCaLamViec;
    private javax.swing.JComboBox<String> jcboChucVu;
    private javax.swing.JComboBox<String> jcboGtinh;
    private javax.swing.JPanel jpnSapXep1;
    private javax.swing.JRadioButton rdoTheoChucVuNV;
    private javax.swing.JRadioButton rdoTheoMaNV;
    private javax.swing.JRadioButton rdoTheoTenNV;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTim;
    private DefaultTableModel modelNV;
    private ButtonGroup btnGr ;
    // End of variables declaration//GEN-END:variables
	@Override
	public void keyTyped(KeyEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void keyPressed(KeyEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void keyReleased(KeyEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void focusGained(FocusEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void focusLost(FocusEvent e) {
		// TODO Auto-generated method stub

	}

	/**
	 *Sá»± kiá»‡n cá»§a click chuá»™t
	 */
	@Override
	public void mouseClicked(MouseEvent e) {
		Object o = e.getSource();
		if (o.equals(jTableNV)) {
            try {
                choose1NV();
            } catch (RemoteException ex) {
                throw new RuntimeException(ex);
            }
        }
	}

	/**
	 * Chá»n 1 dÃ²ng thÃ´ng tin nhÃ¢n viÃªn trong báº£ng danh sÃ¡ch thÃ´ng tin NV
	 */
	private void choose1NV() throws RemoteException {
		int selectedRow = jTableNV.getSelectedRow();
		if(selectedRow >= 0) {
			String maNV = (String) jTableNV.getValueAt(selectedRow, 0);
			ArrayList<NhanVien> lstNV = nhanVienDao.getAllDanhSachNV();
			for(NhanVien nv : lstNV) {
				if(maNV.equals(nv.getMaNhanVien())) {
					txtMaNV.setText(nv.getMaNhanVien());
					txtHoTen.setText(nv.getTenNhanVien());
					txtSDT.setText(nv.getSdt());
					txtDiaChi.setText(nv.getDiaChi());
					jcboChucVu.setSelectedItem(nv.getChucVu());
					txtCCCD.setText(nv.getCccd());
					jcboGtinh.setSelectedItem(nv.getGioiTinh());
					chooserNgaySinh.setDate(nv.getNgaySinh());
					jcboCaLamViec.setSelectedItem(nv.getCaLamViec()+"");
					break;
				}
//				if(trangThai.equals("ÄÃ£ nghá»‰ viá»‡c"))
//					lblNVDaNghiViec.setText("ÄÃƒ NGHá»ˆ VIá»†C.");
//				if(trangThai.equals("Äang lÃ m viá»‡c"))
//					lblNVDaNghiViec.setText("");
			}
		}
	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub

	}
}

